import { InitialRegExpCollection, both } from '../../regex/regexUtil';

export const toRelapseAdviceRegexArray: InitialRegExpCollection[] = [
  { titleText: /I relapsed/i },
  { titleText: /^Major relapse/i },
  { titleText: /^\d+ days relapse/i },

  { ...both, titleText: /lost at \d+ days/i },
  { ...both, titleText: /Relapse... again/i },
  { ...both, titleText: /welp relapsed/i },
  { ...both, titleText: /Worst relapse ever/i },
  { ...both, titleText: /relapse \:\(/i },
  { ...both, titleText: /again 0 days/i },
  { ...both, titleText: /Day (zero|0) Again/i },
  { ...both, titleText: /failed first attempt/i },
  { ...both, titleText: /Failed my \d+ day streak/i },
  { ...both, titleText: /relapse report/i },
  { ...both, titleText: /(I've|just) ?(have)? (relapsed|failed)/i }, // too broad, I failed is way, way too broad

  { ...both, titleText: /(failed|lost) (at|on) day/i },
  { ...both, titleText: /I failed today/i },
  { ...both, titleText: /relapsed hard/i },
  { ...both, titleText: /^relapsed\./i },
  { ...both, titleText: /Relapsed Yet Again/i },
  { ...both, titleText: /^I Failed$/i },
  { ...both, titleText: /^failed again$/i },
  { ...both, titleText: /(broke my|broke a|broke the|lost my|lost a|lost an) ?(.*) (streak)/i },
  { ...both, titleText: /^relapsed\.?$/i },
  { ...both, titleText: /^relapse\.?$/i },
  { ...both, titleText: /^relapsed (last night|today|yesterday)/i },
  { ...both, titleText: /I relapsed (last night|today|yesterday)/i },
  { ...both, titleText: /^failed\.?$/i },
  { ...both, titleText: /Just PMO’d (for|after)/i },
  { ...both, titleText: /I released my load yesterday/i },
  { ...both, titleText: /Full blown relapse/i },
  { ...both, titleText: /I ruined my streak of/i },
  { ...both, titleText: /I recently relapsed/i },
  { ...both, titleText: /After a \d+ (day|days) streak/i },
  { ...both, titleText: /^slipped$/i },
  { ...both, titleText: /Guys I had bad relapse/i },
  { ...both, titleText: /Relapsed now feeling/i },
  { ...both, titleText: /I relapsed a few (hours|minutes)/i },
  { ...both, titleText: /I jerked off today/i },
  { ...both, titleText: /i did a relapse/i },
  { ...both, titleText: /i lost after \d+ days/i },
  { ...both, titleText: /Relapsed on \d+(th)? day/i },
  { ...both, titleText: /I fucking relapsed/i },
  { ...both, titleText: /Relapsed on day \d+/i },
  { ...both, titleText: /and relapsed today/i },
  { ...both, titleText: /Back to day \d+/i },
  { ...both, titleText: /binged \d+ times in/i },
  { ...both, titleText: /I relapsed guys/i },

  { ...both, titleText: /then I relapsed/i },
  { ...both, titleText: /relapsing after a/i },
  { ...both, titleText: /relapsed once again/i },
  { ...both, titleText: /relapsed \d+ times today/i },
  { ...both, titleText: /any tips after a relapse/i },
  { ...both, titleText: /(Relapsed|relapse) at \d+ days/i },
  { ...both, titleText: /(Relapsed|relapse) at day \d+/i },
  { ...both, titleText: /I slipped/i },
  { ...both, titleText: /^Failed after/i },
  { ...both, titleText: /^terrible relapse$/i },
  { ...both, titleText: /made it .* and relapsed/i },
  { ...both, titleText: /my first fail/i },
  { ...both, titleText: /I had a relapse/i },
  { ...both, titleText: /.* made me relapse$/i },
  { ...both, titleText: /back to day (one|1)/i },
  { ...both, titleText: /lost my streak of/i },
  { ...both, titleText: /Failed \.* again/i },
  { ...both, titleText: /Ended my \d+ day streak/i },
  { ...both, titleText: /I lost ?(the)? battle today/i },
  { ...both, titleText: /Gave in last night/i },
  { ...both, titleText: /caved into a relapse already/i },
  { ...both, titleText: /Relaspsed because i had/i },
  { ...both, titleText: /Slipped up again today/i },
  { ...both, titleText: /Goodbye \d+ day streak/i },
  { ...both, titleText: /Relapse on \d+th Day/i },
  { ...both, titleText: /had my longest ever streak end/i },
  { ...both, titleText: /encouragement to start again/i },
  { ...both, titleText: /I relapse on my \d+/i },

  { messageText: /was going strong till today/i },
  { messageText: /Yesterday I relapsed again/i },

  { ...both, titleText: /relapsed (after|on day|again)/i }, // relapsed today DOES NOT work, because it can be used in other contexts.
  { ...both, titleText: /relapse (after|on day)/i }, // relapsed today DOES NOT work, because it can be used in other contexts.

];